name: Feature
description: 🚀 Suggest a new feature.
labels:
- 'type: feature'
body:
- type: markdown
  attributes:
    value: |
      Thank you for opening 🚀 feature request!

- type: textarea
  id: use-cases
  attributes:
    label: Use Cases
    description: |
      In order to properly evaluate a feature request, it is necessary to
      understand the use-cases for it.

      Please describe below the _end goal_ you are trying to achieve that has
      led you to request this feature.

      Please keep this section focused on the problem and not on the suggested
      solution. We'll get to that in a moment, below!

- type: textarea
  id: proposal
  attributes:
    label: Proposal
    description: |
      If you have an idea for a way to address the problem via a change to
      Vector features, please describe it below.

      In this section, it's helpful to include specific examples of how what
      you are suggesting might look in configuration files, or on the command line,
      since that allows us to understand the full picture of what you are proposing.

      If you're not sure of some details, don't worry! When we evaluate the
      feature request we may suggest modifications as necessary to work within the
      design constraints of Vector.

- type: textarea
  id: references
  attributes:
    label: References
    description: |
      Are there any other GitHub issues, whether open or closed, that are
      related to the problem you've described above or to the suggested solution? If
      so, please create a list below that mentions each of them. For example:

      - #7023

