defaults:
  - _self_
  - preprocess: preprocess
  - train: train
  - evaluate: evaluate

# Common parameters
debug_mode: true
input_parameters: rain temperature humidity
project_root_dir_path: /Users/akiranoda/projects/add-hydra-pytorch-pipeline

# Hydra settings
# Disable output directory
hydra:
  output_subdir: null
  run:
    dir: .